use_frameworks!

platform :ios, '9.0'

target 'UIEasy_Example' do
  pod 'UIEasy', :path => '../'

  target 'UIEasy_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'FBSnapshotTestCase'
  end
end
